var _tmr=_tmr||[];
(function(){function p(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function s(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function J(a){(new Image).src=q(a,!0,!1,!1)+";e="+escape("detect")}function e(){}function K(a){if(!t&&"id"in a&&"type"in a&&("pageView"==a.type||"reachGoal"==a.type||"sendEvent"==a.type))t=a.id}function x(a){return a||"https:"==document.location.protocol?"https:":"http:"}function X(a){return(a=
!u?void 0:u[a])&&D?a-D:void 0}function q(a,b,c,d){var k="id"in a?a.id:t,e="url"in a?a.url:location.href,f="referrer"in a?a.referrer:document.referrer,g="title"in a?a.title:document.title;b=x(n)+"//top-fwz1.mail.ru"+(b?"/tracker":"/counter")+"?js=13"+(k?";id="+escape(k):"")+(e?";u="+escape(e):"")+(f?";r="+escape(f):"")+("start"in a&&0<a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(d&&g?";title="+
encodeURIComponent(g):"")+((E=window.screen)?";s="+E.width+"*"+E.height:"")+";vp=";k=d=0;document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(d=document.documentElement.clientWidth,k=document.documentElement.clientHeight):"number"==typeof window.innerWidth&&(d=window.innerWidth,k=window.innerHeight);b=b+(""+d+"*"+k)+";touch="+Y+";hds="+Z+";flash="+F+";sid="+L+";ver="+M;if(c){if(!u||!G)c="";else{c=[];c.push(G.type);c.push(G.redirectCount);c.push(D);
for(d=0;d<N.length;d++)c.push(X(N[d]));c=c.join("/")}c=";nt="+c}else c="";c=b+c+("device"in a?";device="+escape(a.device):"");var h;if("params"in a){b=escape;if(a=a.params)if(d=typeof a,"number"===d||"boolean"===d||"string"===d||a.nodeType||a===a.window)h="";else{k=[];for(h in a)if(a.hasOwnProperty(h)){e=a[h];d=typeof e;if("string"===d)e='"'+e+'"';else if(!("number"===d||"boolean"===d))continue;k.push('"'+h+'":'+e)}h=!k.length?"":"{"+k.join(",")+"}"}else h="";h=";params="+b(h)}else h="";return c+
h+";_="+Math.random()}function O(a,b){return x(n)+"//top-fwz1.mail.ru/tracker?js=13;id="+a[0]+";e="+escape(b)+";sid="+L+";ids="+a.join()+";ver="+M+";_="+Math.random()}function $(){if(!P)for(var a=0;a<r.length;a++){var b=r[a];(new Image).src=q(b,!0,!1,!0)+";e="+escape("PVT/15")}}function Q(){if(!H&&!v){v=!0;for(var a=0;a<r.length;a++)J(r[a])}}function y(){document.addEventListener?(s(document,"DOMContentLoaded",y),_tmr.onready()):document.attachEvent&&"complete"===document.readyState&&(s(document,
"readystatechange",y),_tmr.onready())}function R(){s(window,"load",R);_tmr.onready();_tmr.onload()}function z(){s(window,"unload",z);s(window,"beforeunload",z);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var g=window,f=navigator,aa=document,E,v=!1,ba=function(){function a(a){var c=document.createElement("div");c.setAttribute("class",String.fromCharCode(112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,109,101,100,105,117,109,95,114,101,
99,116,97,110,103,108,101,95,51,48,48,95,50,53,48,32,112,117,98,95,55,50,56,120,57,48,32,108,101,97,100,101,114,98,111,97,114,100,95,55,50,56,95,57,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,95,54,48,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,120,54,48,48,32,116,101,120,116,45,97,100,32,116,101,120,116,65,100,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,97,100,45,
108,105,110,107,115,32,97,100,95,116,101,120,116,32,97,100,95,116,101,120,116,32,98,97,110,110,101,114,95,116,101,120,116,32,116,101,120,116,45,98,97,110,110,101,114));c.setAttribute("style","position: absolute !important; top: -1000px !important; left: -10000px !important; width: 1px !important; height: 1px !important;");this.bait=document.body.appendChild(c);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;
this.loopNumber=0;this.fn=a||null;var d=this;setTimeout(function(){d._checkBait.call(d)},1)}a.prototype._checkBait=function(){if(v)this._stop();else{var a=!1;null!==document.body.getAttribute("abp")||null===this.bait.offsetParent||0==this.bait.offsetHeight||0==this.bait.offsetLeft||0==this.bait.offsetTop||0==this.bait.offsetWidth||0==this.bait.clientHeight||0==this.bait.clientWidth?a=!0:void 0!==window.getComputedStyle&&(a=window.getComputedStyle(this.bait,null),a="none"==a.getPropertyValue("display")||
"hidden"==a.getPropertyValue("visibility"));(!0===a||10<=++this.loopNumber)&&this._stop();if(a&&this.fn)try{this.fn()}catch(c){}else if(!a&&10>this.loopNumber){var d=this;setTimeout(function(){d._checkBait.call(d)},50*this.loopNumber)}}};a.prototype._stop=function(){try{document.body.removeChild(this.bait)}catch(a){}};return function(b){new a(b)}}(),M=60,A=[],I=0,B=0,L="xxxxxxxxxxxxxxxx".replace(/[x]/g,function(a){return(16*Math.random()|0).toString(16)}),C=0,t=0,r=[],m=[],w="string"===typeof location.hostname&&
(-1!=location.hostname.search(/^odnoklassniki\.ru$/)||-1!=location.hostname.search(/\.odnoklassniki\.ru$/)||-1!=location.hostname.search(/^ok\.ru$/)||-1!=location.hostname.search(/\.ok\.ru$/)),n="string"===typeof location.hostname&&(-1!=location.hostname.search(/^vk\.com$/)||-1!=location.hostname.search(/\.vk\.com$/)),S=w||n,P=w||n,ca=w||n,T=w||n,H=!1,Y="ontouchstart"in g||1<(f.maxTouchPoints||f.msMaxTouchPoints)?"1":"0",Z=window.devicePixelRatio||0,F="";if(f.plugins&&f.plugins["Shockwave Flash"])F=
f.plugins["Shockwave Flash"].description.split(" ")[2];else if(window.ActiveXObject)try{var l=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),l=l.GetVariable("$version"),l=l.split(" ")[1].split(","),F=l[0]+"."+l[1]}catch(da){}var g=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},u=g.timing||{},G=g.navigation||{},N="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
D=!u?void 0:u.navigationStart;e.prototype.pageView=function(a){"start"in a&&A.push(a);(new Image).src=q(a,!1,!1,!0);B=(new Date).getTime()};e.prototype.reachGoal=function(a){if("goal"in a&&a.goal){var b="";"value"in a&&a.value&&(b=parseInt(a.value)||"");(new Image).src=q(a,!0,!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal))}};e.prototype.itemView=function(a){if("id"in a||t)(new Image).src=x(0)+"//ad.mail.ru/retarget/?counter="+(a.id||t)+"&list="+(a.list||"")+"&productid="+(a.productid||"")+"&pagetype="+
(a.pagetype||"")+"&totalvalue="+(a.totalvalue||0)+"&_="+Math.random()};e.prototype.sendEvent=function(a){if("category"in a&&a.category&&"action"in a&&a.action){var b=a.category.substr(0,300),c=a.action.substr(0,300),d="";"label"in a&&a.label&&(d=a.label.substr(0,300));var e="";"value"in a&&a.value&&(e=parseInt(a.value)||"");b="CE:"+e+"/"+b.replace(/;/g," ")+";"+c.replace(/;/g," ")+";"+d.replace(/;/g," ");(new Image).src=q(a,!0,!1,!1)+(";e="+escape(b))}};e.prototype.processEvent=function(a){if("type"in
a&&("pageView"!=a.type||"id"in a)){K(a);var b;if(b="id"in a&&"type"in a)if(b="pageView"==a.type)if(b=5>m.length){b:{for(b=0;b<m.length;b++)if(m[b]===a.id){b=!0;break b}b=!1}b=!b}b&&(m.push(a.id),r.push(a),v&&J(a));switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a)}}};e.prototype.push=function(a){this.processEvent(a)};var U=!1;e.prototype.onready=function(){U||(U=!0,!H&&!v&&ba(Q))};
var V=!1;e.prototype.onload=function(){if(!V){V=!0;if(!ca&&0<A.length){C=(new Date).getTime();for(var a=0,b;b=A[a];a++)(new Image).src=q(b,!0,!0,!1)+";e="+escape("RT/load")+";et="+C;B=C;A=[]}P||setTimeout($,15E3)}};e.prototype.beat=function(){if(!S&&0!=m.length&&I){var a=(new Date).getTime(),b=a-I;if(!(12E4<b)){if(12E4<a-B)for(var c=0;c<r.length;c++){var d=r[c];(new Image).src=q(d,!0,!1,!0)+";e="+escape("RT/resend")+";et="+C+";active="+(b?"1":"0")}else(new Image).src=O(m,"RT/beat");B=a}}};var W=!1;
e.prototype.unload=function(){W||(W=!0,!T&&0<m.length&&((new Image).src=O(m,"RT/unload")))};e.prototype.activity=function(a){I=(new Date).getTime()};g=new e;for(f=0;l=_tmr[f];f++)K(l);for(f=0;l=_tmr[f];f++)g.processEvent(l);_tmr=g;(function(){if(!H&&!w&&!n){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=x(n)+"//top-abd.mail.ru/js/advert.js";a.onerror=Q;var b=aa.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}})();if("complete"===document.readyState||
"loading"!==document.readyState&&!document.documentElement.doScroll)_tmr.onready();else document.addEventListener?p(document,"DOMContentLoaded",y):document.attachEvent&&p(document,"readystatechange",y);if("complete"===document.readyState)_tmr.onload();else p(window,"load",R);T||(p(window,"unload",z),p(window,"beforeunload",z));if(!S&&0<m.length){setInterval(_tmr.beat,3E4);try{g=function(a){function b(a){p(document,a,function(){_tmr.activity(a)})}for(var c=0;c<a.length;c++)b(a[c])},g(["scroll","gesturechange",
"touchmove"]),g(["mousedown","mousemove","mouseup"]),p(window,"scroll",function(){_tmr.activity("scallback")})}catch(ea){}}}})();
